version: "3"
services:
        web:
                build: ./app
                container_name: django-interiori-01
                command: python manage.py runserver 0.0.0.0:8000
                volumes:
                        - ./app/:/usr/src/app/
                ports:
                        - 8000:8000
                env_file:
                        - ./config/.env.dev
