version: "3"
services:
        web:
                build: ./app
                container_name: django-interiori-01
                command: python manage.py runserver 0.0.0.0:8000
                volumes:
                        - ./app/:/usr/src/app/
                ports:
                        - 8000:8000
                env_file:
                        - ./config/.env.dev
                depends_on:
                        - db
        db:
                image: postgres:12.0-alpine
                volumes:
                        - postgres_data:/var/lib/postgresql/data/
                environment:
                        - POSTGRES_USER=interiori_dev
                        - POSTGRES_PASSWORD=secr3tP@ssw0rd
                        - POSTGRES_DB=interiori_dev_db
volumes:
        postgres_data:
